--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4

-- Started on 2025-10-29 09:37:54 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = 'public'
    ) THEN
        EXECUTE 'CREATE SCHEMA public';
    END IF;
END
$$;


--
-- TOC entry 218 (class 1259 OID 16386)
-- Name: coffee_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coffee_orders (
    id bigint NOT NULL,
    createdat timestamp(6) without time zone NOT NULL,
    customername character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updatedat timestamp(6) without time zone NOT NULL,
    CONSTRAINT coffee_orders_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'BREWING'::character varying, 'DONE'::character varying])::text[])))
);


--
-- TOC entry 217 (class 1259 OID 16385)
-- Name: coffee_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coffee_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coffee_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3212 (class 2606 OID 16393)
-- Name: coffee_orders coffee_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coffee_orders
    ADD CONSTRAINT coffee_orders_pkey PRIMARY KEY (id);


-- Completed on 2025-10-29 09:37:54 UTC

--
-- PostgreSQL database dump complete
--

