apiVersion: v1
kind: Service
metadata:
  name: coffeequeue-db
  labels:
    app: coffeequeue-db
spec:
  type: ClusterIP
  selector:
    app: coffeequeue-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432

